language: php

php:
  - '7.3'
  - '7.4'

sudo: required
dist: xenial

sudo: required

group: edge

env:
  global:
    - MIN_PHP=7.3.0
    - NODE_VERSION=10

matrix:
  include:
    - php: 7.2
      env: php_extra="7.4"
    - php: 7.3
      env: deps=high
    - php: 7.4
      env: deps=low
    - php: nightly
      services: [memcached]
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache/files

before_install:
  - nvm install $NODE_VERSION
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - composer self-update
  - npm install yarn -g

install:
  - travis_retry composer install --no-interaction --prefer-source
  - yarn install
  - yarn build

script: ./vendor/bin/phpunit --configuration phpunit.xml
