language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

node_js:
  - '8'

matrix:
  allow_failures:
    - php: hhvm

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - npm install bower less grunt-cli -g
  - npm install
  - bower install
  - grunt build

script: ./bin/phpunit --configuration phpunit.xml --coverage-text
