language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - npm install less grunt-cli -g
  - npm install
  - grunt build

script: ./bin/phpunit --configuration phpunit.xml --coverage-text
