version: "2.2"

services:
  phpmyfaq:
    build: .
    stdin_open: true
    links:
      - mariadb
      - elasticsearch
    ports:
      - "8080:80"
    volumes:
      - ./phpmyfaq:/var/www/html
    depends_on:
      - grunt
  grunt:
    image: digitallyseamless/nodejs-bower-grunt
    restart: "no"
    command: grunt build
    stdin_open: true
    tty: true
    volumes:
      - .:/data
    depends_on:
      - yarn
  yarn:
    image: node:8-alpine
    restart: "no"
    command: sh -c "cd app && npm install node-sass -g && yarn install && yarn build"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - composer
  composer:
    image: composer:1.6.1
    restart: "no"
    command: composer install --verbose --no-dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    stdin_open: true
    links:
      - mariadb:db
    ports:
      - "8000:80"
    volumes:
      - ./volumes/sessions:/sessions
  mariadb:
    image: mariadb:10.2.11
    environment:
      - MYSQL_ROOT_PASSWORD=iop
      - MYSQL_DATABASE=phpmyfaq
      - MYSQL_USER=phpmyfaq
      - MYSQL_PASSWORD=phpmyfaq
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:2.4.6
    environment:
      - cluster.name=phpmyfaq-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
